name: Clone

on: [workflow_dispatch]

jobs:
  clone:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone Repository in the location on TerpConnect
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /pub/${{ secrets.USERNAME }}
            git clone git@github.com:1onQ/cmsc389T-web-template.git