name: Delete

on: [workflow_dispatch]

jobs:
  delete:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete the repository from TerpConnect on workflow_dispatch
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /pub/${{ secrets.USERNAME }}
            unalias rm
            rm -rf cmsc389T-web-template